import {$,$$,bytes,ext,isVideoName,safeName,downloadBlob,jsonBlob,debounce,sha256Blob,esc} from './utils.js';
import {idbGet,idbSet,idbClear} from './storage.js';
import {buildRecord,extractGuideStructure} from './file-reader.js';
import {analyzeWithGemini,generateDraftWithGemini,regenerateSection,auditWithGemini,transcribeVideoWithGemini,renderTranscriptAsSource,normalizeFinal} from './gemini.js';
import {connectDrive,isDriveConnected,downloadDriveFile,disconnectDrive} from './drive.js';
import {loadVideoFile,buildVisualEvidence} from './video.js';
import {createDocx,createPdf} from './documents.js';

const base=window.BOT_CONFIG||{};
const SETTINGS_KEY='bot_hardcore_v15_pages_settings';
const defaultSettings={apiKey:base.GEMINI_API_KEY||'',model:base.GEMINI_MODEL||'gemini-flash-latest',videoModel:base.GEMINI_VIDEO_MODEL||'gemini-3.5-flash',visualModel:base.GEMINI_VISUAL_MODEL||'gemini-3.5-flash',googleClientId:base.GOOGLE_OAUTH_CLIENT_ID||''};
let settings={...defaultSettings,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')};
const state={sourceMode:'local',guideFiles:[],guides:[],sourceFile:null,sourceRecord:null,videoFile:null,videoTranscript:null,analysis:null,answers:[],finalDocument:null,audit:null,visualEvidence:[],docxBlob:null,pdfBlob:null,driveMeta:null};
let pendingFinalization=false;

function toast(msg,type='good',ms=3600){const d=document.createElement('div');d.className=`toast ${type}`;d.textContent=msg;$('#toastHost').appendChild(d);setTimeout(()=>d.remove(),ms)}
function warn(host,msg){const x=document.createElement('div');x.className='warning';x.textContent=msg;host.appendChild(x)}
function setStep(n){$$('.step').forEach((x,i)=>x.classList.toggle('active',i<n))}
function show(el,on=true){(typeof el==='string'?$(el):el)?.classList.toggle('hidden',!on)}
function cfgReady(){const ok=!!settings.apiKey;$('#apiStatus').textContent=ok?'Gemini configurado':'Gemini sin configurar';$('#apiStatus').className=`status-chip ${ok?'good':'warn'}`;return ok}
function progressStart(title){show('#progressPanel',true);$('#progressTitle').textContent=title;$('#progressLog').innerHTML='';setProgress(0,'Iniciando…');$('#progressPanel').scrollIntoView({behavior:'smooth',block:'start'})}
function setProgress(p,msg){p=Math.max(0,Math.min(1,p));$('#progressBar').style.width=`${Math.round(p*100)}%`;$('#progressPercent').textContent=`${Math.round(p*100)}%`;if(msg){const d=document.createElement('div');d.textContent=`${new Date().toLocaleTimeString()} · ${msg}`;$('#progressLog').appendChild(d);$('#progressLog').scrollTop=$('#progressLog').scrollHeight}}
function progressEnd(){setProgress(1,'Listo.');setTimeout(()=>show('#progressPanel',false),800)}
function fail(e){console.error(e);show('#progressPanel',false);toast(String(e?.message||e),'bad',6500)}
function ensureApi(){if(!settings.apiKey){$('#settingsDialog').showModal();throw new Error('Configura primero la clave de Gemini.')}}

function loadSettingsUI(){$('#cfgApiKey').value=settings.apiKey;$('#cfgModel').value=settings.model;$('#cfgVideoModel').value=settings.videoModel;$('#cfgVisualModel').value=settings.visualModel;$('#cfgGoogleClientId').value=settings.googleClientId}
function saveSettings(){settings={apiKey:$('#cfgApiKey').value.trim(),model:$('#cfgModel').value.trim()||defaultSettings.model,videoModel:$('#cfgVideoModel').value.trim()||defaultSettings.videoModel,visualModel:$('#cfgVisualModel').value.trim()||defaultSettings.visualModel,googleClientId:$('#cfgGoogleClientId').value.trim()};localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));cfgReady();$('#settingsDialog').close();toast('Configuración guardada.')}

function renderFiles(){
  const gl=$('#guideList');gl.innerHTML=''; if(!state.guideFiles.length){gl.textContent='Aún no hay guías.';gl.className='file-list empty'}else{gl.className='file-list';state.guideFiles.forEach((f,i)=>{const d=document.createElement('div');d.className='file-item';d.innerHTML=`<div><b>${esc(f.name)}</b><small> · ${bytes(f.size)}</small></div><button class="btn ghost small" data-rm-guide="${i}">Quitar</button>`;gl.appendChild(d)})}
  const sl=$('#sourceFileInfo');sl.innerHTML='';if(!state.sourceFile){sl.textContent='Aún no hay origen.';sl.className='file-list empty'}else{sl.className='file-list';sl.innerHTML=`<div class="file-item"><div><b>${esc(state.sourceFile.name)}</b><small> · ${bytes(state.sourceFile.size)}</small></div><button class="btn ghost small" data-rm-source>Quitar</button></div>`}
  $('#uploadHint').textContent=state.guideFiles.length&&(state.sourceFile||state.sourceMode==='drive'&&$('#driveReference').value.trim())?'Listo para analizar.':'Carga al menos una guía y un origen.';
}

async function prepareGuides(){const out=[];for(let i=0;i<state.guideFiles.length;i++){setProgress(.05+.22*(i/state.guideFiles.length),`Leyendo guía ${i+1}/${state.guideFiles.length}: ${state.guideFiles[i].name}`);const r=await buildRecord(state.guideFiles[i],'guide');r.structure=extractGuideStructure(r.text);out.push(r)}state.guides=out;return out}
async function prepareSource(){let file=state.sourceFile;
  if(state.sourceMode==='drive'){
    if(!isDriveConnected())throw new Error('Conecta Google Drive antes de analizar.');
    const ref=$('#driveReference').value.trim();if(!ref)throw new Error('Pega la URL o ID del archivo de Drive.');
    setProgress(.3,'Leyendo metadatos y descargando el origen desde Drive…');const dl=await downloadDriveFile(ref,(m,p)=>setProgress(.30+.15*(p||0),m));file=dl.blob;state.driveMeta=dl.meta;state.sourceFile=file;
  }
  if(!file)throw new Error('Falta el archivo de origen.');
  if(isVideoName(file.name)||file.type.startsWith('video/')){
    state.videoFile=file;const fp=await sha256Blob(file);const cached=await idbGet(`video-transcript:${fp}`);
    if(cached){state.videoTranscript=cached;setProgress(.56,'Transcripcion de video recuperada del checkpoint local.')}else{
      const {transcript}=await transcribeVideoWithGemini({
        apiKey:settings.apiKey,
        model:settings.videoModel,
        file,
        onProgress:(message,p)=>{
          const fraction=Number.isFinite(p)?p:.5;
          setProgress(.32+(.24*fraction),message);
        }
      });
      state.videoTranscript=transcript;
      setProgress(
        .56,
        `Transcripcion lista: ${(transcript.actions||[]).length} acciones detectadas.`
      );
      await idbSet(`video-transcript:${fp}`,transcript);
    }
    const text=renderTranscriptAsSource(state.videoTranscript,file.name);state.sourceRecord={name:file.name,size:file.size,mime:file.type,extension:ext(file.name),kind:'video',fingerprint:fp,text,video_actions:state.videoTranscript.actions||[]};return state.sourceRecord;
  }
  state.videoFile=null;state.videoTranscript=null;setProgress(.42,'Extrayendo texto del documento de origen…');state.sourceRecord=await buildRecord(file,'source');return state.sourceRecord;
}

async function analyze(){try{ensureApi();if(!state.guideFiles.length)throw new Error('Carga al menos una guía.');if(state.guideFiles.length>(base.MAX_GUIDES||8))throw new Error(`Máximo ${base.MAX_GUIDES||8} guías.`);if(state.sourceMode==='local'&&!state.sourceFile)throw new Error('Carga el documento o video de origen.');
  progressStart('Analizando guías y origen');setProgress(.03,'Validando archivos…');const guides=await prepareGuides();const source=await prepareSource();setProgress(.58,'Seleccionando la guía aplicable y comparando evidencia…');const analysis=await analyzeWithGemini({apiKey:settings.apiKey,model:settings.model,guides,source});state.analysis=analysis;state.answers=[];state.finalDocument=null;state.audit=null;state.visualEvidence=[];state.docxBlob=null;state.pdfBlob=null;await saveSnapshot();renderAnalysis();setStep(2);show('#stageAnalysis',true);$('#stageAnalysis').scrollIntoView({behavior:'smooth'});progressEnd();toast('Análisis completado.')
}catch(e){fail(e)}}

function renderAnalysis(){const a=state.analysis;if(!a)return;const req=(a.sections||[]).filter(s=>s.required).length,missing=(a.sections||[]).filter(s=>s.status==='faltante').length,partial=(a.sections||[]).filter(s=>s.status==='parcial').length;
  $('#analysisSummary').innerHTML=metric('Proceso',a.detected_process)+metric('Guía principal',a.selected_guide_name)+metric('Secciones',String(a.sections?.length||0))+metric('Brechas',String(missing+partial));
  const wh=$('#analysisWarnings');wh.innerHTML='';(a.warnings||[]).forEach(x=>warn(wh,x));
  const host=$('#analysisSections');host.innerHTML='';(a.sections||[]).forEach(s=>{const d=document.createElement('div');d.className='analysis-section';const cls=s.status==='completo'?'good':s.status==='parcial'?'warn':'bad';d.innerHTML=`<div class="section-toolbar"><h3>${s.order}. ${esc(s.title)}</h3><span class="badge ${cls}">${esc(s.status)}</span></div><div class="badges">${(s.criteria||[]).map(x=>`<span class="badge">${esc(x)}</span>`).join('')}</div>${s.draft_content?`<p>${esc(s.draft_content)}</p>`:''}${(s.evidence||[]).length?`<div class="evidence"><b>Evidencia:</b> ${(s.evidence||[]).map(esc).join(' · ')}</div>`:''}`;host.appendChild(d)});
  const questions=[];(a.sections||[]).forEach(s=>(s.missing_questions||[]).forEach(q=>questions.push({...q,section_title:s.title})));const qh=$('#questionList');qh.innerHTML='';show('#questionArea',questions.length>0);questions.forEach((q,i)=>{const d=document.createElement('div');d.className='question-card';d.innerHTML=`<label>${esc(q.question)} ${q.required?'<span class="badge bad">requerida</span>':''}</label><p>${esc(q.category||'')} · ${esc(q.why_needed||'')}</p><textarea class="textarea question-answer" rows="2" data-q="${i}" data-section="${esc(q.section_title)}" data-question="${esc(q.question)}" placeholder="Escribe la respuesta verificable…"></textarea>`;qh.appendChild(d)});
}
function metric(k,v){return `<div class="metric"><span>${esc(k)}</span><b>${esc(v||'—')}</b></div>`}
function collectAnswers(){return $$('.question-answer').map(x=>({section_title:x.dataset.section,question:x.dataset.question,answer:x.value.trim()})).filter(x=>x.answer)}

async function generateDraft(){try{ensureApi();if(!state.analysis)throw new Error('Primero analiza los archivos.');state.answers=collectAnswers();progressStart('Generando borrador');setProgress(.12,'Preparando análisis, respuestas y estructura exacta…');setProgress(.3,'Redactando secciones con trazabilidad…');const doc=await generateDraftWithGemini({apiKey:settings.apiKey,model:settings.model,guides:state.guides,source:state.sourceRecord,analysis:state.analysis,answers:state.answers});state.finalDocument=doc;await saveSnapshot();renderDraft();setStep(3);show('#stageDraft',true);$('#stageDraft').scrollIntoView({behavior:'smooth'});progressEnd();toast('Borrador generado.') }catch(e){fail(e)}}

function joinLines(a){return (a||[]).join('\n')}
function renderDraft(){const d=state.finalDocument;if(!d)return;$('#docTitle').value=d.title||'';$('#docSubtitle').value=d.subtitle||'';$('#docIntro').value=d.introductory_note||'';const host=$('#draftSections');host.innerHTML='';(d.sections||[]).forEach((s,i)=>{const el=document.createElement('div');el.className='draft-section';el.dataset.order=s.order;el.innerHTML=`<div class="section-toolbar"><h3>${s.order}. ${esc(s.title)}</h3><button class="btn secondary small regen-section" data-order="${s.order}">✨ Regenerar sección</button></div><div class="draft-grid"><label class="full">Párrafos<textarea class="textarea f-paragraphs" rows="5">${esc(joinLines(s.paragraphs))}</textarea></label><label>Pasos numerados<textarea class="textarea f-numbered" rows="6">${esc(joinLines(s.numbered_items))}</textarea></label><label>Viñetas<textarea class="textarea f-bullets" rows="6">${esc(joinLines(s.bullets))}</textarea></label><label class="full">Tablas (JSON)<textarea class="textarea table-editor f-tables" rows="5">${esc(JSON.stringify(s.tables||[],null,2))}</textarea></label><label class="full">Sustento<textarea class="textarea f-basis" rows="2">${esc(joinLines(s.source_basis))}</textarea></label></div>`;host.appendChild(el)});wireDraftAutosave()}
function lines(v){return String(v||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}
function readDraftFromDom(){const d=normalizeFinal(state.finalDocument||{});d.title=$('#docTitle').value.trim();d.subtitle=$('#docSubtitle').value.trim();d.introductory_note=$('#docIntro').value.trim();d.sections=$$('.draft-section').map((el,i)=>{const old=d.sections[i]||{};let tables=[];try{tables=JSON.parse($('.f-tables',el).value||'[]')}catch{tables=old.tables||[]}return {...old,order:Number(el.dataset.order)||i+1,paragraphs:lines($('.f-paragraphs',el).value),numbered_items:lines($('.f-numbered',el).value),bullets:lines($('.f-bullets',el).value),tables:Array.isArray(tables)?tables:[],source_basis:lines($('.f-basis',el).value)}});return d}
const saveDraftDebounced=debounce(async()=>{if(!state.finalDocument)return;state.finalDocument=readDraftFromDom();await saveSnapshot()},450);
function wireDraftAutosave(){$$('#stageDraft textarea, #stageDraft input').forEach(x=>x.addEventListener('input',saveDraftDebounced));$$('.regen-section').forEach(b=>b.addEventListener('click',()=>regenOne(Number(b.dataset.order),b)))}
async function regenOne(order,button){try{ensureApi();state.finalDocument=readDraftFromDom();button.disabled=true;button.textContent='Regenerando…';const sec=await regenerateSection({apiKey:settings.apiKey,model:settings.model,guides:state.guides,source:state.sourceRecord,analysis:state.analysis,answers:state.answers,document:state.finalDocument,sectionOrder:order});state.finalDocument.sections=state.finalDocument.sections.map(s=>Number(s.order)===order?sec:s);renderDraft();await saveSnapshot();toast('Sección regenerada.')}catch(e){fail(e)}finally{if(button){button.disabled=false;button.textContent='✨ Regenerar sección'}}}

async function finalize(){try{ensureApi();state.finalDocument=readDraftFromDom();progressStart('Auditando y preparando documento final');setProgress(.14,'Guardando tus modificaciones…');setProgress(.28,'Auditando contenido contra la guía…');const audit=await auditWithGemini({apiKey:settings.apiKey,model:settings.model,guides:state.guides,source:state.sourceRecord,analysis:state.analysis,document:state.finalDocument});state.audit=audit;state.finalDocument.validation=audit.validation||state.finalDocument.validation;state.finalDocument.warnings=[...new Set([...(state.finalDocument.warnings||[]),...(audit.warnings||[])])];
  if(state.videoFile&&(state.videoTranscript?.actions||[]).length){const fp=await sha256Blob(state.videoFile);let visuals=await idbGet(`video-visuals:${fp}`);if(!Array.isArray(visuals)||visuals.length!==(state.videoTranscript.actions||[]).length){setProgress(.42,'Preparando video para capturar evidencia visual…');const video=$('#hiddenVideo'),canvas=$('#frameCanvas');await loadVideoFile(state.videoFile,video);visuals=await buildVisualEvidence({apiKey:settings.apiKey,model:settings.visualModel,actions:state.videoTranscript.actions,video,canvas,candidatesPerAction:base.VISUAL_CANDIDATES_PER_ACTION||3,onProgress:(m,p)=>setProgress(.42+.38*p,m)});await idbSet(`video-visuals:${fp}`,visuals)}state.visualEvidence=visuals;renderVisualReview();const manual=visuals.filter(v=>v.status!=='verified').length;if(manual){pendingFinalization=true;show('#visualReview',true);$('#visualReview').scrollIntoView({behavior:'smooth'});setProgress(.84,`${manual} captura(s) requieren confirmación manual.`);show('#progressPanel',false);return}}
  await buildOutputs();
}catch(e){fail(e)}}

function renderVisualReview(){const host=$('#visualItems');host.innerHTML='';const v=state.visualEvidence||[];$('#visualReviewCount').textContent=`${v.filter(x=>x.status==='verified').length} verificadas · ${v.filter(x=>x.status!=='verified').length} manuales`;v.forEach((item,i)=>{const d=document.createElement('div');d.className=`visual-card ${item.status==='verified'?'':'manual'}`;d.innerHTML=`${item.selected?`<img src="${item.selected.dataUrl}" alt="Captura ${esc(item.action_id)}">`:''}<h4>${esc(item.action_id)} · ${esc(item.timestamp||'')}</h4><p>${esc(item.action||'')}</p><div class="badges"><span class="badge ${item.status==='verified'?'good':'warn'}">${esc(item.status)}</span><span class="badge">confianza ${Math.round((item.confidence||0)*100)}%</span></div>${item.status!=='verified'&&item.candidates?.length?`<p>Selecciona el fotograma correcto:</p><div class="candidate-row">${item.candidates.map((c,j)=>`<button class="candidate ${j===item.selected_index?'selected':''}" data-vi="${i}" data-ci="${j}" title="${c.timestamp}"><img src="${c.dataUrl}" alt="${c.timestamp}"></button>`).join('')}</div>`:''}`;host.appendChild(d)});$$('.candidate').forEach(b=>b.addEventListener('click',()=>{const vi=Number(b.dataset.vi),ci=Number(b.dataset.ci),item=state.visualEvidence[vi];item.selected_index=ci;item.selected=item.candidates[ci];item.status='manual_review';renderVisualReview()}))}

async function buildOutputs(){progressStart('Generando Word y PDF');setProgress(.86,'Aplicando formato institucional…');const guide=state.guides[state.analysis.selected_guide_index];const template=guide?.extension==='docx'?guide.file:null;state.docxBlob=await createDocx(state.finalDocument,{templateFile:template,visualEvidence:state.visualEvidence});setProgress(.93,'Creando PDF paginado…');state.pdfBlob=await createPdf(state.finalDocument,{visualEvidence:state.visualEvidence});await saveSnapshot();renderFinal();setStep(4);show('#stageFinal',true);show('#visualReview',false);$('#stageFinal').scrollIntoView({behavior:'smooth'});progressEnd();toast('Documento final generado.');pendingFinalization=false}

function renderFinal(){const d=state.finalDocument,a=state.audit||{};const counts={cumple:0,parcial:0,no_aplica:0};(d.validation||[]).forEach(x=>{if(counts[x.status]!=null)counts[x.status]++});const total=Object.values(counts).reduce((x,y)=>x+y,0);$('#finalSummary').innerHTML=metric('Secciones',String(d.sections?.length||0))+metric('Cumple',String(counts.cumple))+metric('Parcial',String(counts.parcial))+metric('No aplica',String(counts.no_aplica));$('#finalCompliance').textContent=total?`${counts.cumple}/${total} criterios cumplen`:'Documento generado';$('#auditSummary').textContent=a.editorial_summary||'Documento generado con trazabilidad a la guía y al origen.';const wh=$('#finalWarnings');wh.innerHTML='';(d.warnings||[]).forEach(x=>warn(wh,x));$('#docxSize').textContent=state.docxBlob?bytes(state.docxBlob.size):'DOCX';$('#pdfSize').textContent=state.pdfBlob?bytes(state.pdfBlob.size):'PDF';$('#finalPreview').innerHTML=previewHtml(d)}
function previewHtml(d){return `<article class="doc-preview"><h1>${esc(d.title)}</h1>${d.subtitle?`<p style="text-align:center"><i>${esc(d.subtitle)}</i></p>`:''}${d.introductory_note?`<p>${esc(d.introductory_note)}</p>`:''}${(d.sections||[]).map(s=>`<section><h2>${s.order}. ${esc(s.title)}</h2>${(s.paragraphs||[]).map(x=>`<p>${esc(x)}</p>`).join('')}${(s.numbered_items||[]).length?`<ol>${s.numbered_items.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>`:''}${(s.bullets||[]).length?`<ul>${s.bullets.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}${(s.tables||[]).map(t=>`<h4>${esc(t.title||'')}</h4><table><thead><tr>${(t.headers||[]).map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${(t.rows||[]).map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`).join('')}</section>`).join('')}</article>`}

async function saveSnapshot(){const snap={analysis:state.analysis,answers:state.answers,finalDocument:state.finalDocument,audit:state.audit,sourceRecord:state.sourceRecord?{...state.sourceRecord,file:undefined}:null,guides:state.guides.map(g=>({name:g.name,text:g.text,extension:g.extension,structure:g.structure,fingerprint:g.fingerprint})),savedAt:new Date().toISOString()};await idbSet('project-snapshot',snap)}
async function maybeRestore(){const s=await idbGet('project-snapshot');if(!s?.analysis)return;state.analysis=s.analysis;state.answers=s.answers||[];state.finalDocument=s.finalDocument||null;state.audit=s.audit||null;state.sourceRecord=s.sourceRecord||null;state.guides=s.guides||[];renderAnalysis();show('#stageAnalysis',true);setStep(state.finalDocument?3:2);if(state.finalDocument){renderDraft();show('#stageDraft',true)}toast('Se recuperó el último borrador local. Vuelve a seleccionar los archivos si necesitas regenerar Word/PDF.', 'good',5000)}

async function resetAll(){if(!confirm('¿Reiniciar el proceso y borrar checkpoints locales de este navegador?'))return;Object.assign(state,{sourceMode:'local',guideFiles:[],guides:[],sourceFile:null,sourceRecord:null,videoFile:null,videoTranscript:null,analysis:null,answers:[],finalDocument:null,audit:null,visualEvidence:[],docxBlob:null,pdfBlob:null,driveMeta:null});await idbClear();$('#guideFiles').value='';$('#sourceFile').value='';$('#driveReference').value='';renderFiles();['#stageAnalysis','#stageDraft','#visualReview','#stageFinal','#progressPanel'].forEach(x=>show(x,false));setStep(1);window.scrollTo({top:0,behavior:'smooth'});toast('Proceso reiniciado.')}

function wire(){
  $('#appTitle').textContent=base.title||'Generador documental inteligente';$('#appSubtitle').textContent=base.subtitle||'';$('#maxGuidesLabel').textContent=base.MAX_GUIDES||8;cfgReady();loadSettingsUI();renderFiles();
  $('#btnSettings').addEventListener('click',()=>{loadSettingsUI();$('#settingsDialog').showModal()});$('#btnSaveSettings').addEventListener('click',saveSettings);$('#btnClearSettings').addEventListener('click',()=>{localStorage.removeItem(SETTINGS_KEY);settings={...defaultSettings};loadSettingsUI();cfgReady();toast('Configuración local borrada.')});$('#btnReset').addEventListener('click',resetAll);
  $('#guideFiles').addEventListener('change',e=>{const incoming=[...e.target.files].filter(f=>['pdf','docx','txt'].includes(ext(f.name)));state.guideFiles=[...state.guideFiles,...incoming].slice(0,base.MAX_GUIDES||8);e.target.value='';renderFiles()});
  $('#sourceFile').addEventListener('change',e=>{state.sourceFile=e.target.files?.[0]||null;renderFiles()});
  document.addEventListener('click',e=>{const rg=e.target.closest('[data-rm-guide]');if(rg){state.guideFiles.splice(Number(rg.dataset.rmGuide),1);renderFiles()}if(e.target.closest('[data-rm-source]')){state.sourceFile=null;$('#sourceFile').value='';renderFiles()}});
  $$('.seg[data-source-mode]').forEach(b=>b.addEventListener('click',()=>{state.sourceMode=b.dataset.sourceMode;$$('.seg[data-source-mode]').forEach(x=>x.classList.toggle('active',x===b));show('#localSourcePane',state.sourceMode==='local');show('#driveSourcePane',state.sourceMode==='drive');renderFiles()}));
  $('#driveReference').addEventListener('input',renderFiles);$('#btnConnectDrive').addEventListener('click',async()=>{try{await connectDrive(settings.googleClientId);$('#driveStatus').textContent='Conectado';toast('Google Drive conectado.')}catch(e){fail(e)}});if(isDriveConnected())$('#driveStatus').textContent='Conectado';
  $('#btnAnalyze').addEventListener('click',analyze);$('#btnGenerateDraft').addEventListener('click',generateDraft);$('#btnBackAnalysis').addEventListener('click',()=>$('#stageAnalysis').scrollIntoView({behavior:'smooth'}));$('#btnFinalize').addEventListener('click',finalize);$('#btnContinueAfterVisual').addEventListener('click',async()=>{try{await buildOutputs()}catch(e){fail(e)}});
  $('#btnExportAnalysis').addEventListener('click',()=>state.analysis&&downloadBlob(jsonBlob(state.analysis),'analisis_guia.json'));
  $('#btnDownloadDocx').addEventListener('click',()=>state.docxBlob&&downloadBlob(state.docxBlob,`${safeName(state.finalDocument?.title)}.docx`));$('#btnDownloadPdf').addEventListener('click',()=>state.pdfBlob&&downloadBlob(state.pdfBlob,`${safeName(state.finalDocument?.title)}.pdf`));$('#btnDownloadProject').addEventListener('click',()=>downloadBlob(jsonBlob({version:'github-pages-direct-v15',analysis:state.analysis,answers:state.answers,finalDocument:state.finalDocument,audit:state.audit,source:{name:state.sourceRecord?.name,fingerprint:state.sourceRecord?.fingerprint},savedAt:new Date().toISOString()}),'proyecto_bot_hardcore_v15.json'));
  ['dragenter','dragover'].forEach(ev=>$$('.dropzone').forEach(z=>z.addEventListener(ev,e=>{e.preventDefault();z.classList.add('drag')})));['dragleave','drop'].forEach(ev=>$$('.dropzone').forEach(z=>z.addEventListener(ev,e=>{e.preventDefault();z.classList.remove('drag')})));
}

wire();maybeRestore().catch(console.warn);
