import {xmlEsc, dataUrlToBytes, safeName, bytes, downloadBlob} from './utils.js';

function p(text='',style='',opts={}){const st=style?`<w:pStyle w:val="${style}"/>`:'';const jc=opts.center?'<w:jc w:val="center"/>':'';const bold=opts.bold?'<w:b/>':'';const italic=opts.italic?'<w:i/>':'';const sz=opts.size?`<w:sz w:val="${opts.size}"/><w:szCs w:val="${opts.size}"/>`:'';return `<w:p><w:pPr>${st}${jc}</w:pPr><w:r><w:rPr>${bold}${italic}${sz}</w:rPr><w:t xml:space="preserve">${xmlEsc(text)}</w:t></w:r></w:p>`}
function tableXml(t){const headers=t.headers||[],rows=t.rows||[];if(!headers.length)return'';const cell=v=>`<w:tc><w:tcPr><w:tcW w:w="0" w:type="auto"/></w:tcPr>${p(v)}</w:tc>`;const row=r=>`<w:tr>${r.map(cell).join('')}</w:tr>`;return `<w:tbl><w:tblPr><w:tblBorders><w:top w:val="single" w:sz="4" w:color="AAB4C2"/><w:left w:val="single" w:sz="4" w:color="AAB4C2"/><w:bottom w:val="single" w:sz="4" w:color="AAB4C2"/><w:right w:val="single" w:sz="4" w:color="AAB4C2"/><w:insideH w:val="single" w:sz="4" w:color="D0D6DF"/><w:insideV w:val="single" w:sz="4" w:color="D0D6DF"/></w:tblBorders></w:tblPr>${row(headers)}${rows.map(r=>row([...r,...Array(Math.max(0,headers.length-r.length)).fill('')].slice(0,headers.length))).join('')}</w:tbl>`}
function imageXml(rId,id,label='Evidencia'){const cx=5486400,cy=3086100;return `<w:p><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:drawing><wp:inline xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" distT="0" distB="0" distL="0" distR="0"><wp:extent cx="${cx}" cy="${cy}"/><wp:docPr id="${id}" name="${xmlEsc(label)}"/><a:graphic xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:nvPicPr><pic:cNvPr id="${id}" name="${xmlEsc(label)}.jpg"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" r:embed="${rId}"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="${cx}" cy="${cy}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>`}

function minimalStyles(){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:rPr><w:sz w:val="22"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:basedOn w:val="Normal"/><w:rPr><w:b/><w:sz w:val="34"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:basedOn w:val="Normal"/><w:rPr><w:b/><w:sz w:val="28"/></w:rPr></w:style></w:styles>`}
function minimalDoc(body,sectPr=''){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><w:body>${body}${sectPr||'<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="720" w:footer="720" w:gutter="0"/></w:sectPr>'}</w:body></w:document>`}

export async function createDocx(finalDoc,{templateFile=null,visualEvidence=[]}={}){
  if(!window.JSZip)throw new Error('JSZip no cargó.');
  const zip=new JSZip(); let template=false; let originalDoc=''; let rels=''; let contentTypes=''; let sectPr='';
  if(templateFile&&/\.docx$/i.test(templateFile.name)){
    const z=await JSZip.loadAsync(await templateFile.arrayBuffer());
    for(const [name,item] of Object.entries(z.files)){if(!item.dir)zip.file(name,await item.async('uint8array'))}
    originalDoc=await z.file('word/document.xml')?.async('text')||'';
    rels=await z.file('word/_rels/document.xml.rels')?.async('text')||'';
    contentTypes=await z.file('[Content_Types].xml')?.async('text')||'';
    const m=originalDoc.match(/<w:sectPr\b[\s\S]*?<\/w:sectPr>/i);sectPr=m?m[0]:'';template=true;
  } else {
    contentTypes=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="jpg" ContentType="image/jpeg"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>`;
    zip.file('[Content_Types].xml',contentTypes);zip.file('_rels/.rels',`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`);zip.file('word/styles.xml',minimalStyles());
    rels=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`;
  }
  if(!/Extension="jpg"/i.test(contentTypes)){contentTypes=contentTypes.replace('</Types>','<Default Extension="jpg" ContentType="image/jpeg"/></Types>');zip.file('[Content_Types].xml',contentTypes)}
  let maxRid=0;for(const m of rels.matchAll(/Id="rId(\d+)"/g))maxRid=Math.max(maxRid,Number(m[1]));let imgId=1000;let body='';let visualIndex=0;const visualSection=(finalDoc.sections||[]).reduce((best,s)=>((s.numbered_items||[]).length>(best?.numbered_items||[]).length?s:best),null);const visualSectionOrder=visualSection?.order;
  body+=p(finalDoc.title||'Documento generado','',{center:true,bold:true,size:34});if(finalDoc.subtitle)body+=p(finalDoc.subtitle,'',{center:true,italic:true});if(finalDoc.introductory_note)body+=p(finalDoc.introductory_note);
  for(const sec of finalDoc.sections||[]){body+=p(`${sec.order}. ${sec.title}`,'',{bold:true,size:28});for(const x of sec.paragraphs||[])body+=p(x);for(let i=0;i<(sec.numbered_items||[]).length;i++){body+=p(`${sec.order}.${i+1}. ${sec.numbered_items[i]}`);const vis=Number(sec.order)===Number(visualSectionOrder)?visualEvidence[visualIndex++]:null;if(vis?.selected?.dataUrl){const rid=`rId${++maxRid}`;const fname=`media/evidence_${String(visualIndex).padStart(4,'0')}.jpg`;zip.file(`word/${fname}`,dataUrlToBytes(vis.selected.dataUrl));rels=rels.replace('</Relationships>',`<Relationship Id="${rid}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="${fname}"/></Relationships>`);body+=imageXml(rid,++imgId,`${vis.action_id||'Evidencia'} ${vis.timestamp||''}`);body+=p(`Evidencia visual · ${vis.action_id||''} · ${vis.selected.timestamp||vis.timestamp||''}`,'',{center:true,italic:true,size:18})}}
    for(const x of sec.bullets||[])body+=p(`• ${x}`);for(const t of sec.tables||[]){if(t.title)body+=p(t.title,'',{bold:true});body+=tableXml(t)}if((sec.source_basis||[]).length)body+=p(`Sustento: ${(sec.source_basis||[]).join(' | ')}`,'',{italic:true,size:18});
  }
  let docXml=minimalDoc(body,sectPr);
  if(template&&originalDoc){docXml=originalDoc.replace(/<w:body\b[^>]*>[\s\S]*?<\/w:body>/i,`<w:body>${body}${sectPr}</w:body>`)}
  zip.file('word/document.xml',docXml);zip.file('word/_rels/document.xml.rels',rels);
  return await zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',compression:'DEFLATE',compressionOptions:{level:6}});
}

export async function createPdf(finalDoc,{visualEvidence=[]}={}){
  if(!window.jspdf?.jsPDF)throw new Error('jsPDF no cargó.');
  const {jsPDF}=window.jspdf;const pdf=new jsPDF({unit:'mm',format:'a4'});const W=210,H=297,L=18,R=18,T=18,B=18;let y=T;let visualIndex=0;const visualSection=(finalDoc.sections||[]).reduce((best,s)=>((s.numbered_items||[]).length>(best?.numbered_items||[]).length?s:best),null);const visualSectionOrder=visualSection?.order;
  const pageBreak=(need=10)=>{if(y+need>H-B){pdf.addPage();y=T}};
  const text=(s,size=10,opts={})=>{pdf.setFont('helvetica',opts.bold?'bold':opts.italic?'italic':'normal');pdf.setFontSize(size);const lines=pdf.splitTextToSize(String(s||''),W-L-R);pageBreak(lines.length*5+3);pdf.text(lines,opts.center?W/2:L,y,{align:opts.center?'center':'left'});y+=lines.length*(size*.42)+3};
  text(finalDoc.title||'Documento generado',17,{bold:true,center:true});if(finalDoc.subtitle)text(finalDoc.subtitle,11,{italic:true,center:true});y+=3;if(finalDoc.introductory_note)text(finalDoc.introductory_note,10);
  for(const sec of finalDoc.sections||[]){pageBreak(16);text(`${sec.order}. ${sec.title}`,13,{bold:true});for(const x of sec.paragraphs||[])text(x,10);for(let i=0;i<(sec.numbered_items||[]).length;i++){text(`${sec.order}.${i+1}. ${sec.numbered_items[i]}`,10);const vis=Number(sec.order)===Number(visualSectionOrder)?visualEvidence[visualIndex++]:null;if(vis?.selected?.dataUrl){pageBreak(58);try{pdf.addImage(vis.selected.dataUrl,'JPEG',L,y,W-L-R,50,undefined,'FAST');y+=53;text(`Evidencia visual · ${vis.action_id||''} · ${vis.selected.timestamp||vis.timestamp||''}`,8,{italic:true,center:true})}catch{}}}for(const x of sec.bullets||[])text(`• ${x}`,10);for(const t of sec.tables||[]){if(t.title)text(t.title,10,{bold:true});const rows=[t.headers||[],...(t.rows||[])].filter(r=>r.length);for(const row of rows){text(row.join('  |  '),8)} }if((sec.source_basis||[]).length)text(`Sustento: ${(sec.source_basis||[]).join(' | ')}`,8,{italic:true});}
  const total=pdf.getNumberOfPages();for(let i=1;i<=total;i++){pdf.setPage(i);pdf.setFontSize(8);pdf.setTextColor(100);pdf.text(`Página ${i} de ${total}`,W-R,H-8,{align:'right'});pdf.setTextColor(0)}
  return pdf.output('blob');
}

export function downloadOutputs({docxBlob,pdfBlob,title}){const base=safeName(title||'documento');if(docxBlob)downloadBlob(docxBlob,`${base}.docx`);if(pdfBlob)setTimeout(()=>downloadBlob(pdfBlob,`${base}.pdf`),250)}
export {bytes};
